# Generated by Django 4.0.4 on 2022-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='holder_kt',
            field=models.CharField(default='091000-2020', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='holder_name',
            field=models.CharField(default='Kári Georgsson', max_length=255),
            preserve_default=False,
        ),
    ]
