# Generated by Django 4.0.4 on 2022-05-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_holder_kt_ticket_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='tickets',
            field=models.CharField(max_length=255),
        ),
    ]
