# Generated by Django 4.0.4 on 2022-05-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_booking'),
        ('booking', '0003_alter_bookings_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='bookerid',
        ),
        migrations.AddField(
            model_name='bookings',
            name='booker',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
            preserve_default=False,
        ),
    ]
