# Generated by Django 4.0.4 on 2022-05-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookings_bookerid_bookings_booker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='tickets',
            new_name='tickets_id',
        ),
    ]
