# Generated by Django 4.0.4 on 2022-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_bookings_booker_bookings_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='tickets_id',
        ),
    ]
