# Generated by Django 4.0.4 on 2022-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_bookings_tickets_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='delivery_method',
            field=models.CharField(default='postal_service', max_length=255),
            preserve_default=False,
        ),
    ]
