# Generated by Django 4.0.4 on 2022-06-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookings_city_alter_bookings_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
