# Generated by Django 4.0.4 on 2022-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=9999)),
                ('favorite_categories', models.CharField(max_length=9999)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
