# Generated by Django 4.0.4 on 2022-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='booking',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
