# Generated by Django 4.0.4 on 2022-05-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_users_username_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
