# Generated by Django 4.0.4 on 2022-05-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_users_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
