# Generated by Django 4.0.4 on 2022-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorite_categories',
            field=models.CharField(default='asdfasdfafd', max_length=9999),
            preserve_default=False,
        ),
    ]
