# Generated by Django 4.0.4 on 2022-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
