# Generated by Django 4.0.4 on 2022-06-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_users_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
