# Generated by Django 4.0.4 on 2022-06-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
