# Generated by Django 4.0.4 on 2022-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maximum_attendees',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='prices',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default='2022-06-24 16:00:00.416000 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='types',
            field=models.CharField(default='child', max_length=255),
            preserve_default=False,
        ),
    ]
