# Generated by Django 4.0.4 on 2022-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_lat_alter_event_long_alter_event_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.CharField(default='This is a dummy description', max_length=9999),
            preserve_default=False,
        ),
    ]
